_BASE_: "../Base-MGN.yml"

MODEL:
  BACKBONE:
    WITH_IBN: False
    EXTRA_BN: True
  PIXEL_MEAN: [89.896, 79.200, 80.073]
  PIXEL_STD: [63.872, 64.305, 63.839]
  WEIGHTS: '/home/ubuntu/Nilay/PersonReIDModels/LUPerson/fast-reid/checkpoints/market.pth'
  DEVICE: 'cuda:0'
INPUT:
  REA:
    MEAN: [0.0, 0.0, 0.0]
  DO_AUTOAUG: False
SOLVER:
  HEADS_LR_FACTOR: 1.0
  BACKBONE_BN_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: -1

DATASETS:
  NAMES: ("CMDM",)
  TESTS: ("CMDM",)
  KWARGS: 'data_name:market'
  ROOT: "./datasets"

TEST:
  EVAL_PERIOD: 60
  RERANK:
    ENABLED: True
    K1: 20
    K2: 6
    LAMBDA: 0.3
  CACHE:
    ENABLED: True
    CACHE_DIR: "logs/final/train/market/cache"
    REUSE_FEAT: True
    PARALLEL:
      ENABLED: True
      NUM_WORKERS: 6
  
OUTPUT_DIR: "logs/final/train/market"